# Generated by Django 6.0.1 on 2026-02-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('join_date', models.DateField()),
            ],
            options={
                'db_table': 'employees',
                'ordering': ['-join_date'],
            },
        ),
    ]
